[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx prisma db push --accept-data-loss && node prisma/import_railway.js && node dist/src/main.js"
