import { PrismaClient, TireType, TireStatus } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Iniciando carga de 20 neumáticos de prueba para la flota...');

  // 1. Obtener vehículos existentes para asignación
  const vehicles = await prisma.vehicle.findMany({ take: 10 });
  const v1 = vehicles[0]?.id || null; // e.g. AA-123-OK
  const v2 = vehicles[1]?.id || null; // e.g. AB-987-ZZ
  const v3 = vehicles[2]?.id || null; // e.g. AC-555-XX

  // Eliminar neumáticos previos de prueba si existen
  await prisma.tireMovement.deleteMany({});
  await prisma.tireRetread.deleteMany({});
  await prisma.tireInspection.deleteMany({});
  await prisma.tire.deleteMany({});

  const tireSeedData = [
    // 1. En Depósito - Nuevo
    {
      codigoInterno: 'T-000101',
      codigoQR: 'QR-T-000101-2026',
      numeroSerie: 'SN-MCH-9901',
      marca: 'Michelin',
      modelo: 'X Multi Z',
      medida: '295/80 R22.5',
      tipo: TireType.DIRECCIONAL,
      status: TireStatus.EN_DEPOSITO,
      fechaCompra: new Date('2026-01-10'),
      proveedor: 'Michelin Argentina S.A.',
      precioCompra: 480000,
      profundidadInicialMm: 14.0,
      profundidadActualMm: 14.0,
      presionRecomendadaPsi: 110,
      presionActualPsi: 110,
      kilometrosRecorridos: 0,
      cantidadRecapados: 0,
    },
    // 2. Instalado en Vehículo 1 (E1_IZQ)
    {
      codigoInterno: 'T-000102',
      codigoQR: 'QR-T-000102-2026',
      numeroSerie: 'SN-MCH-9902',
      marca: 'Michelin',
      modelo: 'X Multi Z',
      medida: '295/80 R22.5',
      tipo: TireType.DIRECCIONAL,
      status: TireStatus.INSTALADO,
      vehicleId: v1,
      posicion: 'E1_IZQ',
      fechaCompra: new Date('2025-08-15'),
      proveedor: 'Michelin Argentina S.A.',
      precioCompra: 480000,
      profundidadInicialMm: 14.0,
      profundidadActualMm: 12.5,
      presionRecomendadaPsi: 110,
      presionActualPsi: 108,
      kilometrosRecorridos: 15400,
      cantidadRecapados: 0,
    },
    // 3. Instalado en Vehículo 1 (E1_DER)
    {
      codigoInterno: 'T-000103',
      codigoQR: 'QR-T-000103-2026',
      numeroSerie: 'SN-MCH-9903',
      marca: 'Michelin',
      modelo: 'X Multi Z',
      medida: '295/80 R22.5',
      tipo: TireType.DIRECCIONAL,
      status: TireStatus.INSTALADO,
      vehicleId: v1,
      posicion: 'E1_DER',
      fechaCompra: new Date('2025-08-15'),
      proveedor: 'Michelin Argentina S.A.',
      precioCompra: 480000,
      profundidadInicialMm: 14.0,
      profundidadActualMm: 12.2,
      presionRecomendadaPsi: 110,
      presionActualPsi: 110,
      kilometrosRecorridos: 15400,
      cantidadRecapados: 0,
    },
    // 4-7. Tracción Instalados en Vehículo 1
    {
      codigoInterno: 'T-000104',
      codigoQR: 'QR-T-000104-2026',
      numeroSerie: 'SN-GDY-8801',
      marca: 'Goodyear',
      modelo: 'KMAX D',
      medida: '295/80 R22.5',
      tipo: TireType.TRACCION,
      status: TireStatus.INSTALADO,
      vehicleId: v1,
      posicion: 'E2_IZQ_EXT',
      fechaCompra: new Date('2025-05-20'),
      proveedor: 'Neumáticos del Centro',
      precioCompra: 440000,
      profundidadInicialMm: 15.0,
      profundidadActualMm: 9.8,
      presionRecomendadaPsi: 115,
      presionActualPsi: 115,
      kilometrosRecorridos: 32000,
      cantidadRecapados: 0,
    },
    {
      codigoInterno: 'T-000105',
      codigoQR: 'QR-T-000105-2026',
      numeroSerie: 'SN-GDY-8802',
      marca: 'Goodyear',
      modelo: 'KMAX D',
      medida: '295/80 R22.5',
      tipo: TireType.TRACCION,
      status: TireStatus.INSTALADO,
      vehicleId: v1,
      posicion: 'E2_IZQ_INT',
      fechaCompra: new Date('2025-05-20'),
      proveedor: 'Neumáticos del Centro',
      precioCompra: 440000,
      profundidadInicialMm: 15.0,
      profundidadActualMm: 9.5,
      presionRecomendadaPsi: 115,
      presionActualPsi: 112,
      kilometrosRecorridos: 32000,
      cantidadRecapados: 0,
    },
    {
      codigoInterno: 'T-000106',
      codigoQR: 'QR-T-000106-2026',
      numeroSerie: 'SN-GDY-8803',
      marca: 'Goodyear',
      modelo: 'KMAX D',
      medida: '295/80 R22.5',
      tipo: TireType.TRACCION,
      status: TireStatus.INSTALADO,
      vehicleId: v1,
      posicion: 'E2_DER_INT',
      fechaCompra: new Date('2025-05-20'),
      proveedor: 'Neumáticos del Centro',
      precioCompra: 440000,
      profundidadInicialMm: 15.0,
      profundidadActualMm: 9.6,
      presionRecomendadaPsi: 115,
      presionActualPsi: 115,
      kilometrosRecorridos: 32000,
      cantidadRecapados: 0,
    },
    {
      codigoInterno: 'T-000107',
      codigoQR: 'QR-T-000107-2026',
      numeroSerie: 'SN-GDY-8804',
      marca: 'Goodyear',
      modelo: 'KMAX D',
      medida: '295/80 R22.5',
      tipo: TireType.TRACCION,
      status: TireStatus.INSTALADO,
      vehicleId: v1,
      posicion: 'E2_DER_EXT',
      fechaCompra: new Date('2025-05-20'),
      proveedor: 'Neumáticos del Centro',
      precioCompra: 440000,
      profundidadInicialMm: 15.0,
      profundidadActualMm: 9.4,
      presionRecomendadaPsi: 115,
      presionActualPsi: 114,
      kilometrosRecorridos: 32000,
      cantidadRecapados: 0,
    },
    // 8-9. Remolque Instalados en Vehículo 2
    {
      codigoInterno: 'T-000108',
      codigoQR: 'QR-T-000108-2026',
      numeroSerie: 'SN-FTE-7701',
      marca: 'Fate',
      modelo: 'Cargo SR-260',
      medida: '295/80 R22.5',
      tipo: TireType.REMOLQUE,
      status: TireStatus.INSTALADO,
      vehicleId: v2,
      posicion: 'E1_IZQ',
      fechaCompra: new Date('2024-11-10'),
      proveedor: 'Fate Distribuidora',
      precioCompra: 390000,
      profundidadInicialMm: 14.0,
      profundidadActualMm: 7.2,
      presionRecomendadaPsi: 110,
      presionActualPsi: 108,
      kilometrosRecorridos: 48500,
      cantidadRecapados: 0,
    },
    {
      codigoInterno: 'T-000109',
      codigoQR: 'QR-T-000109-2026',
      numeroSerie: 'SN-FTE-7702',
      marca: 'Fate',
      modelo: 'Cargo SR-260',
      medida: '295/80 R22.5',
      tipo: TireType.REMOLQUE,
      status: TireStatus.INSTALADO,
      vehicleId: v2,
      posicion: 'E1_DER',
      fechaCompra: new Date('2024-11-10'),
      proveedor: 'Fate Distribuidora',
      precioCompra: 390000,
      profundidadInicialMm: 14.0,
      profundidadActualMm: 7.0,
      presionRecomendadaPsi: 110,
      presionActualPsi: 110,
      kilometrosRecorridos: 48500,
      cantidadRecapados: 0,
    },
    // 10. Neumático con 1 Recapado Completado en Depósito
    {
      codigoInterno: 'T-000110',
      codigoQR: 'QR-T-000110-2026',
      numeroSerie: 'SN-PIR-6601',
      marca: 'Pirelli',
      modelo: 'TR:01',
      medida: '295/80 R22.5',
      tipo: TireType.TRACCION,
      status: TireStatus.EN_DEPOSITO,
      fechaCompra: new Date('2024-03-01'),
      proveedor: 'Pirelli Neumáticos',
      precioCompra: 420000,
      profundidadInicialMm: 15.0,
      profundidadActualMm: 13.5,
      presionRecomendadaPsi: 115,
      presionActualPsi: 115,
      kilometrosRecorridos: 65000,
      cantidadRecapados: 1,
    },
    // 11. Actualmente En Taller de Recapado
    {
      codigoInterno: 'T-000111',
      codigoQR: 'QR-T-000111-2026',
      numeroSerie: 'SN-BS-5501',
      marca: 'Bridgestone',
      modelo: 'R268',
      medida: '295/80 R22.5',
      tipo: TireType.DIRECCIONAL,
      status: TireStatus.EN_RECAPADO,
      fechaCompra: new Date('2024-01-15'),
      proveedor: 'Bridgestone Oficial',
      precioCompra: 460000,
      profundidadInicialMm: 14.0,
      profundidadActualMm: 2.5,
      presionRecomendadaPsi: 110,
      presionActualPsi: 100,
      kilometrosRecorridos: 78000,
      cantidadRecapados: 1,
    },
    // 12-13. Desgaste Crítico (<3.0 mm) Instalados en Vehículo 3
    {
      codigoInterno: 'T-000112',
      codigoQR: 'QR-T-000112-2026',
      numeroSerie: 'SN-CNT-4401',
      marca: 'Continental',
      modelo: 'HSR2',
      medida: '295/80 R22.5',
      tipo: TireType.DIRECCIONAL,
      status: TireStatus.INSTALADO,
      vehicleId: v3,
      posicion: 'E1_IZQ',
      fechaCompra: new Date('2024-04-10'),
      proveedor: 'Continental Tires',
      precioCompra: 470000,
      profundidadInicialMm: 14.0,
      profundidadActualMm: 2.4,
      presionRecomendadaPsi: 110,
      presionActualPsi: 105,
      kilometrosRecorridos: 82000,
      cantidadRecapados: 0,
    },
    {
      codigoInterno: 'T-000113',
      codigoQR: 'QR-T-000113-2026',
      numeroSerie: 'SN-CNT-4402',
      marca: 'Continental',
      modelo: 'HSR2',
      medida: '295/80 R22.5',
      tipo: TireType.DIRECCIONAL,
      status: TireStatus.INSTALADO,
      vehicleId: v3,
      posicion: 'E1_DER',
      fechaCompra: new Date('2024-04-10'),
      proveedor: 'Continental Tires',
      precioCompra: 470000,
      profundidadInicialMm: 14.0,
      profundidadActualMm: 2.2,
      presionRecomendadaPsi: 110,
      presionActualPsi: 105,
      kilometrosRecorridos: 82000,
      cantidadRecapados: 0,
    },
    // 14. Rueda Auxiliar
    {
      codigoInterno: 'T-000114',
      codigoQR: 'QR-T-000114-2026',
      numeroSerie: 'SN-FTE-7703',
      marca: 'Fate',
      modelo: 'Cargo SR-260',
      medida: '295/80 R22.5',
      tipo: TireType.AUXILIAR,
      status: TireStatus.INSTALADO,
      vehicleId: v1,
      posicion: 'AUXILIAR_1',
      fechaCompra: new Date('2025-09-01'),
      proveedor: 'Fate Distribuidora',
      precioCompra: 390000,
      profundidadInicialMm: 14.0,
      profundidadActualMm: 11.0,
      presionRecomendadaPsi: 110,
      presionActualPsi: 110,
      kilometrosRecorridos: 5000,
      cantidadRecapados: 0,
    },
    // 15-16. Stock en Depósito Central
    {
      codigoInterno: 'T-000115',
      codigoQR: 'QR-T-000115-2026',
      numeroSerie: 'SN-MCH-9905',
      marca: 'Michelin',
      modelo: 'X Multi D',
      medida: '295/80 R22.5',
      tipo: TireType.TRACCION,
      status: TireStatus.EN_DEPOSITO,
      fechaCompra: new Date('2026-02-01'),
      proveedor: 'Michelin Argentina S.A.',
      precioCompra: 510000,
      profundidadInicialMm: 15.0,
      profundidadActualMm: 15.0,
      presionRecomendadaPsi: 115,
      presionActualPsi: 115,
      kilometrosRecorridos: 0,
      cantidadRecapados: 0,
    },
    {
      codigoInterno: 'T-000116',
      codigoQR: 'QR-T-000116-2026',
      numeroSerie: 'SN-MCH-9906',
      marca: 'Michelin',
      modelo: 'X Multi D',
      medida: '295/80 R22.5',
      tipo: TireType.TRACCION,
      status: TireStatus.EN_DEPOSITO,
      fechaCompra: new Date('2026-02-01'),
      proveedor: 'Michelin Argentina S.A.',
      precioCompra: 510000,
      profundidadInicialMm: 15.0,
      profundidadActualMm: 15.0,
      presionRecomendadaPsi: 115,
      presionActualPsi: 115,
      kilometrosRecorridos: 0,
      cantidadRecapados: 0,
    },
    // 17. Dado de Baja por Deformación / Daño
    {
      codigoInterno: 'T-000117',
      codigoQR: 'QR-T-000117-2026',
      numeroSerie: 'SN-GDY-8809',
      marca: 'Goodyear',
      modelo: 'KMAX S',
      medida: '295/80 R22.5',
      tipo: TireType.DIRECCIONAL,
      status: TireStatus.DADO_DE_BAJA,
      fechaCompra: new Date('2023-11-10'),
      proveedor: 'Neumáticos del Centro',
      precioCompra: 410000,
      profundidadInicialMm: 14.0,
      profundidadActualMm: 0.0,
      presionRecomendadaPsi: 110,
      presionActualPsi: 0,
      kilometrosRecorridos: 94000,
      cantidadRecapados: 2,
    },
    // 18. 2º Recapado Completado en Depósito
    {
      codigoInterno: 'T-000118',
      codigoQR: 'QR-T-000118-2026',
      numeroSerie: 'SN-PIR-6608',
      marca: 'Pirelli',
      modelo: 'FG:01',
      medida: '295/80 R22.5',
      tipo: TireType.TRACCION,
      status: TireStatus.EN_DEPOSITO,
      fechaCompra: new Date('2023-06-20'),
      proveedor: 'Pirelli Neumáticos',
      precioCompra: 400000,
      profundidadInicialMm: 15.0,
      profundidadActualMm: 12.0,
      presionRecomendadaPsi: 115,
      presionActualPsi: 115,
      kilometrosRecorridos: 110000,
      cantidadRecapados: 2,
    },
    // 19. En Reparación en Taller
    {
      codigoInterno: 'T-000119',
      codigoQR: 'QR-T-000119-2026',
      numeroSerie: 'SN-BS-5509',
      marca: 'Bridgestone',
      modelo: 'M726',
      medida: '295/80 R22.5',
      tipo: TireType.TRACCION,
      status: TireStatus.EN_REPARACION,
      fechaCompra: new Date('2024-08-05'),
      proveedor: 'Bridgestone Oficial',
      precioCompra: 450000,
      profundidadInicialMm: 15.0,
      profundidadActualMm: 5.5,
      presionRecomendadaPsi: 115,
      presionActualPsi: 80,
      kilometrosRecorridos: 52000,
      cantidadRecapados: 0,
    },
    // 20. Desmontado a Depósito
    {
      codigoInterno: 'T-000120',
      codigoQR: 'QR-T-000120-2026',
      numeroSerie: 'SN-FTE-7709',
      marca: 'Fate',
      modelo: 'Cargo Express',
      medida: '295/80 R22.5',
      tipo: TireType.REMOLQUE,
      status: TireStatus.EN_DEPOSITO,
      fechaCompra: new Date('2024-09-12'),
      proveedor: 'Fate Distribuidora',
      precioCompra: 380000,
      profundidadInicialMm: 14.0,
      profundidadActualMm: 4.2,
      presionRecomendadaPsi: 110,
      presionActualPsi: 110,
      kilometrosRecorridos: 58000,
      cantidadRecapados: 1,
    },
  ];

  for (const item of tireSeedData) {
    const tire = await prisma.tire.create({ data: item });

    // Crear Movimiento de Alta / Compra
    await prisma.tireMovement.create({
      data: {
        tireId: tire.id,
        tipoMovimiento: 'COMPRA',
        posicionDestino: 'DEPÓSITO CENTRAL',
        profundidadMm: tire.profundidadInicialMm,
        presionPsi: tire.presionRecomendadaPsi,
        costo: tire.precioCompra,
        motivo: 'Alta inicial por compra de neumático',
        createdAt: tire.fechaCompra,
      },
    });

    // Si está instalado, agregar movimiento de Instalación e Inspección
    if (tire.status === TireStatus.INSTALADO) {
      await prisma.tireMovement.create({
        data: {
          tireId: tire.id,
          vehicleId: tire.vehicleId,
          tipoMovimiento: 'INSTALACION',
          posicionOrigen: 'DEPÓSITO CENTRAL',
          posicionDestino: `Vehículo (${tire.posicion})`,
          profundidadMm: tire.profundidadInicialMm,
          presionPsi: tire.presionRecomendadaPsi,
          motivo: `Montaje preventivo en posición ${tire.posicion}`,
          createdAt: new Date(tire.fechaCompra.getTime() + 10 * 24 * 60 * 60 * 1000),
        },
      });

      await prisma.tireInspection.create({
        data: {
          tireId: tire.id,
          vehicleId: tire.vehicleId,
          fecha: new Date(),
          inspector: 'Ing. Carlos Gómez',
          profundidadMm: tire.profundidadActualMm,
          presionPsi: tire.presionActualPsi || tire.presionRecomendadaPsi,
          estadoVisual: tire.profundidadActualMm <= 3.0 ? 'REEMPLAZAR' : 'BUENO',
          resultado: tire.profundidadActualMm <= 3.0 ? 'DEBE_REEMPLAZARSE' : 'CORRECTO',
          observaciones: 'Inspección de rutina en taller',
        },
      });
    }

    // Si tiene recapados, registrar historial de recapados y movimiento
    if (tire.cantidadRecapados > 0) {
      await prisma.tireRetread.create({
        data: {
          tireId: tire.id,
          empresaRecapadora: 'Bandag Recapados S.A.',
          numeroRecapado: tire.cantidadRecapados,
          fechaEnvio: new Date('2025-09-01'),
          fechaRecepcion: new Date('2025-09-15'),
          costo: 180000,
          profundidadNuevaMm: 14.0,
          status: 'COMPLETADO',
          observaciones: 'Banda restaurada con garantía Bandag',
        },
      });

      await prisma.tireMovement.create({
        data: {
          tireId: tire.id,
          tipoMovimiento: 'RECEPCION_RECAPADO',
          posicionOrigen: 'RECAPADORA: Bandag',
          posicionDestino: 'DEPÓSITO CENTRAL',
          profundidadMm: 14.0,
          costo: 180000,
          motivo: `Retorno de recapado #${tire.cantidadRecapados}`,
          createdAt: new Date('2025-09-15'),
        },
      });
    }
  }

  console.log('✅ 20 Neumáticos de prueba creados exitosamente con movimientos e historial completo.');
}

main()
  .catch((e) => {
    console.error('❌ Error en seed de neumáticos:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
